data_augment:
- ALONG_AXIS_LIST:
  - x
  NAME: random_world_flip
- NAME: random_world_rotation
  WORLD_ROT_ANGLE:
  - -0.78539816
  - 0.78539816
- NAME: random_world_scaling
  WORLD_SCALE_RANGE:
  - 0.95
  - 1.05
fusion:
  args:
    cur_ego_pose_flag: true
  core_method: IntermediateFusionDatasetSCOPE
loss:
  args:
    cls_weight: 1.0
    reg: 2.0
  core_method: point_pillar_loss
lr_scheduler:
  core_method: multistep
  gamma: 0.1
  step_size:
  - 15
  - 30
model:
  args:
    anchor_num: 2
    anchor_number: 2
    backbone_fix: false
    base_bev_backbone:
      compression: 0
      layer_nums: &id001
      - 3
      - 5
      - 8
      layer_strides:
      - 2
      - 2
      - 2
      num_filters: &id002
      - 64
      - 128
      - 256
      num_upsample_filter:
      - 128
      - 128
      - 128
      upsample_strides:
      - 1
      - 2
      - 4
    lidar_range: &id004
    - -140.8
    - -40
    - -3
    - 140.8
    - 40
    - 1
    pillar_vfe:
      num_filters:
      - 64
      use_absolute_xyz: true
      use_norm: true
      with_distance: false
    point_pillar_scatter:
      grid_size: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 3
        - !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          wAIAAAAAAADIAAAAAAAAAAEAAAAAAAAA
      num_features: 64
    voxel_size: &id003
    - 0.4
    - 0.4
    - 4
    async_mode: true
  core_method: point_pillar_intermediate_scope
name: OPV2V_point_pillar_Attentive_Fusion_async200_gpu2
optimizer:
  args:
    eps: 1.0e-10
    weight_decay: 0.0001
  core_method: Adam
  lr: 0.002
postprocess:
  anchor_args:
    D: 1
    H: 200
    W: 704
    cav_lidar_range: *id004
    feature_stride: 2
    h: 1.56
    l: 3.9
    num: 2
    r:
    - 0
    - 90
    vd: 4
    vh: 0.4
    vw: 0.4
    w: 1.6
  core_method: VoxelPostprocessor
  # gt_range: *id004
  max_num: 100
  nms_thresh: 0.15
  order: hwl
  target_args:
    neg_threshold: 0.45
    pos_threshold: 0.6
    score_threshold: 0.23
preprocess:
  args:
    max_points_per_voxel: 32
    max_voxel_test: 70000
    max_voxel_train: 32000
    voxel_size: *id003
  cav_lidar_range: *id004
  core_method: SpVoxelPreprocessor
root_dir: ./data/OPV2V_new/train
train_params:
  batch_size: 4
  epoches: 20
  frame: 2
  max_cav: 5
  eval_freq: 1
  save_freq: 1
validate_dir: ./data/OPV2V_new/test
wild_setting:
  async: false
  async_overhead: 100
  backbone_delay: 10
  data_size: 1.06
  loc_err: false
  ryp_std: 0.2
  seed: 20
  transmission_speed: 27
  xyz_std: 0.2
yaml_parser: load_point_pillar_params
